env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - xo
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 13
plugins:
  - import
rules:
  arrow-parens: 0
  object-curly-spacing: 0
  import/no-unresolved: [ 2, { commonjs: true } ]
