env:
  es6: true
  node: true
extends:
  - xo
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 2017
plugins:
  - import
rules:
  arrow-parens: 0
  object-curly-spacing: 0
  import/no-unresolved: [ 2, { commonjs: true } ]
