module.exports = {
	rules: {
		'arrow-parens': 0,
		'import/extensions': 0,
		'n/prefer-global/process': 0,
		'n/prefer-promises/fs': 0,
		'object-curly-spacing': 0,
		'unicorn/no-anonymous-default-export': 0,
		'unicorn/no-array-callback-reference': 0,
		'unicorn/no-array-method-this-argument': 0,
		'unicorn/no-typeof-undefined': 0,
		'unicorn/prefer-module': 0,
		'unicorn/prefer-native-coercion-functions': 0,
		'unicorn/prefer-string-replace-all': 0,
		'unicorn/prevent-abbreviations': 0,
		'unicorn/switch-case-braces': 0,
		'@stylistic/object-curly-spacing': ['error', 'always'],
		'@stylistic/arrow-parens': ['error', 'always'],
	},
};
